project:
  type: website
  output-dir: _site

website:
  title: "Mo Wazzi"
  site-url: "https://mowazzi.github.io"
  description: "Mo Wazzi is a PhD student in Economics at the University of Oxford and Nuffield College."
  page-footer:
    left: "© 2026 Mo Wazzi"
    right: "University of Oxford · Nuffield College"

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: false
    link-external-newwindow: true

execute:
  freeze: auto
